import pandas as pd
import tkinter as tk
from tkinter import filedialog

# -------------------------------
# CATEGORY KEYWORD DEFINITIONS
# -------------------------------
CATEGORY_KEYWORDS = {
    "Housing: Rent / Mortgage": ["rent", "wohnung", "verwaltung"],
    "Housing: Electricity": ["ewz", "strom", "electricity"],
    "Housing: Water": ["wasser", "water utility"],
    "Housing: Maintenance & Repairs": ["maintenance", "repair", "hauswartung"],

    "Utilities: Phone": ["mobile", "handy", "phone", "swisscom"],
    "Utilities: WiFi": ["internet", "wifi", "sunrise"],

    "Health & Medical: Health Insurance": ["insurance", "krankenkasse", "css"],
    "Health & Medical: Doctor Visits": ["doctor", "permanence", "arzt"],
    "Health & Medical: Medication": ["pharmacy", "pharma", "amavita"],
    "Health & Medical: Dental / Vision": ["dentist", "dental", "vision"],

    "Financial Obligations: Debt Payments": ["debt", "loan"],
    "Financial Obligations: Savings Contributions": ["pillar", "3a", "savings"],
    "Financial Obligations: Investments": ["investment", "trading", "broker"],
    "Financial Obligations: Taxes": ["steueramt", "tax"],

    "Groceries / Personal Care": ["migros", "coop", "denner", "gidor", "drogerie"],

    "Entertainment & Social: Dining Out": ["restaurant", "dinner", "essen", "food"],
    "Entertainment & Social: Movies / Events / Concerts": ["movie", "pathé", "cinema", "concert"],
    "Entertainment & Social: Coffee / Snacks": ["coffee", "starbucks", "café"],
    "Entertainment & Social: Subscriptions": ["spotify", "netflix", "abo"],
    "Entertainment & Social: Hobbies": ["hobby", "craft"],
    "Entertainment & Social: Travel / Vacations": ["sbb", "travel", "hotel", "flight"],

    "Transport and Car: Gas / Fuel": ["avia", "fuel", "gas", "tankstelle"],
    "Transport and Car: Parking / Tolls": ["parking", "parkhaus", "toll"],
    "Transport and Car: Public transport": ["zvv", "vbz", "bus", "tram"],
    "Transport and Car: Vehicle Insurance": ["insurance"],

    "Clothing": ["zara", "globus", "clothing"],

    "Miscellaneous: Gifts": ["gift", "geschenk"],
    "Miscellaneous: Donations": ["donation", "spende"]
}

# -------------------------------
# CATEGORY MATCHING FUNCTION
# -------------------------------
def auto_categorize(text):
    text = text.lower()
    for category, keywords in CATEGORY_KEYWORDS.items():
        for kw in keywords:
            if kw in text:
                return category
    return None


# -------------------------------
# MAIN PROGRAM
# -------------------------------
def main():
    print("ZKB Transaction Categorizer")
    print("Please select the CSV file generated by Code 1.\n")

    # File picker
    root = tk.Tk()
    root.withdraw()
    file_path = filedialog.askopenfilename(
        filetypes=[("CSV Files", "*.csv")]
    )

    if not file_path:
        print("No file selected. Exiting.")
        return

    print(f"Loading: {file_path}")

    # READ CSV (matches Code 1)
    df = pd.read_csv(
        file_path,
        sep=",",
        encoding="utf-8",
        dtype=str
    )

    # Verify required columns exist
    required_columns = [
        "Date", "Booking text", "ZKB reference", "Reference number",
        "Debit CHF", "Credit CHF", "Value date", "Balance CHF"
    ]

    for col in required_columns:
        if col not in df.columns:
            raise ValueError(f"Missing required column: {col}")

    # Add Category column
    df["Category"] = ""

    for i, row in df.iterrows():
        booking_text = str(row["Booking text"])

        category = auto_categorize(booking_text)

        if category:
            df.at[i, "Category"] = category
            continue

        # Prompt user for uncategorized transactions
        print("\n----------------------------------")
        print("Uncategorized transaction:")
        print(booking_text)
        print("----------------------------------")

        categories = list(CATEGORY_KEYWORDS.keys())
        for idx, cat in enumerate(categories, 1):
            print(f"{idx}. {cat}")
        print(f"{len(categories) + 1}. Other")

        try:
            choice = int(input("Select category number: "))
            if 1 <= choice <= len(categories):
                df.at[i, "Category"] = categories[choice - 1]
            else:
                df.at[i, "Category"] = "Other"
        except ValueError:
            df.at[i, "Category"] = "Other"

    # SAVE OUTPUT (comma-separated, UTF-8)
    output_path = file_path.replace(".csv", "_categorized.csv")
    df.to_csv(output_path, index=False, encoding="utf-8")

    print(f"\nCategorized file saved to:\n{output_path}")
    print("Done!")


if __name__ == "__main__":
    main()